services:
  quotes-be:
    build:
      context: ./quotes-be
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: pgvector/pgvector:pg18-trixie
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-quotes_be}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-quotes_be}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
